### PR TITLE
Resolve dependencies using project’s instead of lib’s context (fix #1)

### LINKED ISSUE #1: Don't resolve project dependencies using metal-cli's node_modules as root
Currently the `resolve` function is trying to resolve dependencies on the context of the tool (metal-cli) instead of on the context of the scanned process. This leads to metal-cli including incorrect dependencies when transpiling modules.

For instance, try to include isobject as a dependency in a metal-cli enabled project and you will get the isobject from metal-cli instead of the one from your project.

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
This fixes #1

**Review by jbalsas — APPROVED** [review]

**Comment by jbalsas** [comment]
LGTM!

**Review by brunobasto — COMMENTED** [review]
Hey @izaera, do you think it's possible to add a test case for this change? I realize it can be tricky..

**Comment by izaera** [comment]
I asked myself the same, but it looked quite difficult how because you need to download the library under test (babel-preset-metal-resolve-source) as a dev dependency of another project and then look into the resolved modules of such project.

I suppose it could be done, but I consider it too much effort for no real gain (apart from avoiding someone breaking it again if she/he doesn't look at the commit history). 

What do you think @brunobasto ?

**Review by brunobasto — APPROVED** [review]
@izaera, yeah, I figured it would not be trivial. I think it should be fine then. Thx!

**Pull request merged**
